export enum PromptSectionType {
  SYSTEM_PROMPT = 'SYSTEM_PROMPT',
  ASSISTANT_IDENTITY = 'ASSISTANT_IDENTITY',
  USER_PROFILE = 'USER_PROFILE',
  CONVERSATION_SUMMARY = 'CONVERSATION_SUMMARY',
  CONVERSATION_HISTORY = 'CONVERSATION_HISTORY',
  RELEVANT_MEMORIES = 'RELEVANT_MEMORIES',
  RELEVANT_TASKS = 'RELEVANT_TASKS',
  RELEVANT_KNOWLEDGE = 'RELEVANT_KNOWLEDGE',
  ACTIVE_PROJECT = 'ACTIVE_PROJECT',
  USER_PROMPT = 'USER_PROMPT',
  OUTPUT_INSTRUCTIONS = 'OUTPUT_INSTRUCTIONS',
}

export const PROMPT_SECTION_ORDER: Record<PromptSectionType, number> = {
  [PromptSectionType.SYSTEM_PROMPT]: 1,
  [PromptSectionType.ASSISTANT_IDENTITY]: 2,
  [PromptSectionType.USER_PROFILE]: 3,
  [PromptSectionType.CONVERSATION_SUMMARY]: 4,
  [PromptSectionType.CONVERSATION_HISTORY]: 5,
  [PromptSectionType.RELEVANT_MEMORIES]: 6,
  [PromptSectionType.RELEVANT_TASKS]: 7,
  [PromptSectionType.RELEVANT_KNOWLEDGE]: 8,
  [PromptSectionType.ACTIVE_PROJECT]: 9,
  [PromptSectionType.USER_PROMPT]: 10,
  [PromptSectionType.OUTPUT_INSTRUCTIONS]: 11,
};
