import { Home, MemoryStick, MessageSquare, BookOpen, CalendarDays, Settings, Plus, FileText } from "lucide-react";
import type { CommandItem } from "../types/command";

export const COMMAND_ITEMS: CommandItem[] = [
  {
    id: "navigate-home",
    label: "Home",
    description: "Go to the home dashboard",
    icon: <Home className="size-4" />,
    category: "pages",
    keywords: ["home", "dashboard", "main"],
    route: "/app/home",
    action: () => {},
  },
  {
    id: "navigate-tasks",
    label: "Tasks",
    description: "View and manage your tasks",
    icon: <CalendarDays className="size-4" />,
    category: "pages",
    keywords: ["tasks", "todo", "to-do", "task"],
    route: "/app/tasks",
    action: () => {},
  },
  {
    id: "navigate-memory",
    label: "Memory",
    description: "Access your memory vault",
    icon: <MemoryStick className="size-4" />,
    category: "pages",
    keywords: ["memory", "mem", "vault", "remember"],
    route: "/app/memory",
    action: () => {},
  },
  {
    id: "navigate-knowledge",
    label: "Knowledge",
    description: "Browse your knowledge base",
    icon: <BookOpen className="size-4" />,
    category: "pages",
    keywords: ["knowledge", "know", "docs", "documents", "library"],
    route: "/app/knowledge",
    action: () => {},
  },
  {
    id: "navigate-assistant",
    label: "Assistant",
    description: "Chat with your AI assistant",
    icon: <MessageSquare className="size-4" />,
    category: "pages",
    keywords: ["assistant", "assist", "chat", "ai", "help"],
    route: "/app/assistant",
    action: () => {},
  },
  {
    id: "navigate-journal",
    label: "Journal",
    description: "Write in your journal",
    icon: <FileText className="size-4" />,
    category: "pages",
    keywords: ["journal", "diary", "write", "entry"],
    route: "/app/journal",
    action: () => {},
  },
  {
    id: "navigate-settings",
    label: "Settings",
    description: "Manage your preferences",
    icon: <Settings className="size-4" />,
    category: "pages",
    keywords: ["settings", "preferences", "config", "options"],
    route: "/app/settings",
    action: () => {},
  },
  {
    id: "action-new-task",
    label: "New Task",
    description: "Create a new task",
    icon: <Plus className="size-4" />,
    category: "actions",
    keywords: ["new", "create", "add", "task"],
    route: "/app/tasks",
    action: () => {
      window.dispatchEvent(new CustomEvent("open-new-task-dialog"));
    },
  },
  {
    id: "action-open-assistant",
    label: "Open Assistant",
    description: "Quickly open the assistant",
    icon: <MessageSquare className="size-4" />,
    category: "actions",
    keywords: ["open", "assistant", "chat"],
    route: "/app/assistant",
    action: () => {},
  },
  {
    id: "action-open-memory",
    label: "Open Memory",
    description: "Quickly open memory",
    icon: <MemoryStick className="size-4" />,
    category: "actions",
    keywords: ["open", "memory"],
    route: "/app/memory",
    action: () => {},
  },
  {
    id: "action-open-knowledge",
    label: "Open Knowledge",
    description: "Quickly open knowledge base",
    icon: <BookOpen className="size-4" />,
    category: "actions",
    keywords: ["open", "knowledge"],
    route: "/app/knowledge",
    action: () => {},
  },
  {
    id: "action-open-journal",
    label: "Open Journal",
    description: "Quickly open journal",
    icon: <FileText className="size-4" />,
    category: "actions",
    keywords: ["open", "journal"],
    route: "/app/journal",
    action: () => {},
  },
  {
    id: "action-open-settings",
    label: "Open Settings",
    description: "Quickly open settings",
    icon: <Settings className="size-4" />,
    category: "actions",
    keywords: ["open", "settings"],
    route: "/app/settings",
    action: () => {},
  },
];

export const COMMAND_GROUPS = [
  { category: "pages" as const, label: "Pages" },
  { category: "actions" as const, label: "Actions" },
  { category: "recent" as const, label: "Recent" },
  { category: "favorites" as const, label: "Favorites" },
];

export const RECENT_STORAGE_KEY = "lifeos-command-recent";
export const FAVORITES_STORAGE_KEY = "lifeos-command-favorites";
export const MAX_RECENT_ITEMS = 8;